services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=user          
      - POSTGRES_PASSWORD=password  
      - POSTGRES_DB=vocbl     
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d vocbl"]
      interval: 5s
      timeout: 5s
      retries: 5

  nats:
    image: nats:latest
    command: >
      -js
      -m 8222
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats-data:/data
    healthcheck:
      test: ["CMD", "nats", "server", "check", "jetstream"]
      interval: 5s
      timeout: 5s
      retries: 5

  nats-setup:
    image: natsio/nats-box:latest
    entrypoint: >
      sh -c "
        echo 'Waiting for NATS...';
        sleep 10;

        nats --server nats:4222 stream add SPECIALISTS --subjects 'user.*' --storage file --retention limits --max-age 168h --defaults || true;

        echo 'NATS JetStream Setup Complete';
      "
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5

volumes:
  nats-data:
  opensearch-data:
  redis-data: