// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: api/v1/onboard.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Onboard_CheckUsernameAvailability_FullMethodName = "/onboard.v1.Onboard/CheckUsernameAvailability"
	Onboard_Register_FullMethodName                  = "/onboard.v1.Onboard/Register"
	Onboard_RegisterGoogle_FullMethodName            = "/onboard.v1.Onboard/RegisterGoogle"
	Onboard_RestartVerification_FullMethodName       = "/onboard.v1.Onboard/RestartVerification"
	Onboard_CancelRegistration_FullMethodName        = "/onboard.v1.Onboard/CancelRegistration"
	Onboard_CompleteVerification_FullMethodName      = "/onboard.v1.Onboard/CompleteVerification"
)

// OnboardClient is the client API for Onboard service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OnboardClient interface {
	CheckUsernameAvailability(ctx context.Context, in *CheckUsernameAvailabilityRequest, opts ...grpc.CallOption) (*CheckUsernameAvailabilityResponse, error)
	Register(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*RegistrationSession, error)
	RegisterGoogle(ctx context.Context, in *GoogleRegistrationRequest, opts ...grpc.CallOption) (*RegistrationSession, error)
	RestartVerification(ctx context.Context, in *RegistrationSession, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CancelRegistration(ctx context.Context, in *RegistrationSession, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CompleteVerification(ctx context.Context, in *VerificationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type onboardClient struct {
	cc grpc.ClientConnInterface
}

func NewOnboardClient(cc grpc.ClientConnInterface) OnboardClient {
	return &onboardClient{cc}
}

func (c *onboardClient) CheckUsernameAvailability(ctx context.Context, in *CheckUsernameAvailabilityRequest, opts ...grpc.CallOption) (*CheckUsernameAvailabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckUsernameAvailabilityResponse)
	err := c.cc.Invoke(ctx, Onboard_CheckUsernameAvailability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onboardClient) Register(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*RegistrationSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistrationSession)
	err := c.cc.Invoke(ctx, Onboard_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onboardClient) RegisterGoogle(ctx context.Context, in *GoogleRegistrationRequest, opts ...grpc.CallOption) (*RegistrationSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistrationSession)
	err := c.cc.Invoke(ctx, Onboard_RegisterGoogle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onboardClient) RestartVerification(ctx context.Context, in *RegistrationSession, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Onboard_RestartVerification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onboardClient) CancelRegistration(ctx context.Context, in *RegistrationSession, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Onboard_CancelRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onboardClient) CompleteVerification(ctx context.Context, in *VerificationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Onboard_CompleteVerification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OnboardServer is the server API for Onboard service.
// All implementations must embed UnimplementedOnboardServer
// for forward compatibility.
type OnboardServer interface {
	CheckUsernameAvailability(context.Context, *CheckUsernameAvailabilityRequest) (*CheckUsernameAvailabilityResponse, error)
	Register(context.Context, *RegistrationRequest) (*RegistrationSession, error)
	RegisterGoogle(context.Context, *GoogleRegistrationRequest) (*RegistrationSession, error)
	RestartVerification(context.Context, *RegistrationSession) (*emptypb.Empty, error)
	CancelRegistration(context.Context, *RegistrationSession) (*emptypb.Empty, error)
	CompleteVerification(context.Context, *VerificationRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedOnboardServer()
}

// UnimplementedOnboardServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOnboardServer struct{}

func (UnimplementedOnboardServer) CheckUsernameAvailability(context.Context, *CheckUsernameAvailabilityRequest) (*CheckUsernameAvailabilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckUsernameAvailability not implemented")
}
func (UnimplementedOnboardServer) Register(context.Context, *RegistrationRequest) (*RegistrationSession, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedOnboardServer) RegisterGoogle(context.Context, *GoogleRegistrationRequest) (*RegistrationSession, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterGoogle not implemented")
}
func (UnimplementedOnboardServer) RestartVerification(context.Context, *RegistrationSession) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartVerification not implemented")
}
func (UnimplementedOnboardServer) CancelRegistration(context.Context, *RegistrationSession) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelRegistration not implemented")
}
func (UnimplementedOnboardServer) CompleteVerification(context.Context, *VerificationRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteVerification not implemented")
}
func (UnimplementedOnboardServer) mustEmbedUnimplementedOnboardServer() {}
func (UnimplementedOnboardServer) testEmbeddedByValue()                 {}

// UnsafeOnboardServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OnboardServer will
// result in compilation errors.
type UnsafeOnboardServer interface {
	mustEmbedUnimplementedOnboardServer()
}

func RegisterOnboardServer(s grpc.ServiceRegistrar, srv OnboardServer) {
	// If the following call panics, it indicates UnimplementedOnboardServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Onboard_ServiceDesc, srv)
}

func _Onboard_CheckUsernameAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUsernameAvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnboardServer).CheckUsernameAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Onboard_CheckUsernameAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnboardServer).CheckUsernameAvailability(ctx, req.(*CheckUsernameAvailabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Onboard_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnboardServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Onboard_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnboardServer).Register(ctx, req.(*RegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Onboard_RegisterGoogle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoogleRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnboardServer).RegisterGoogle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Onboard_RegisterGoogle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnboardServer).RegisterGoogle(ctx, req.(*GoogleRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Onboard_RestartVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistrationSession)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnboardServer).RestartVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Onboard_RestartVerification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnboardServer).RestartVerification(ctx, req.(*RegistrationSession))
	}
	return interceptor(ctx, in, info, handler)
}

func _Onboard_CancelRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistrationSession)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnboardServer).CancelRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Onboard_CancelRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnboardServer).CancelRegistration(ctx, req.(*RegistrationSession))
	}
	return interceptor(ctx, in, info, handler)
}

func _Onboard_CompleteVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnboardServer).CompleteVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Onboard_CompleteVerification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnboardServer).CompleteVerification(ctx, req.(*VerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Onboard_ServiceDesc is the grpc.ServiceDesc for Onboard service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Onboard_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "onboard.v1.Onboard",
	HandlerType: (*OnboardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckUsernameAvailability",
			Handler:    _Onboard_CheckUsernameAvailability_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Onboard_Register_Handler,
		},
		{
			MethodName: "RegisterGoogle",
			Handler:    _Onboard_RegisterGoogle_Handler,
		},
		{
			MethodName: "RestartVerification",
			Handler:    _Onboard_RestartVerification_Handler,
		},
		{
			MethodName: "CancelRegistration",
			Handler:    _Onboard_CancelRegistration_Handler,
		},
		{
			MethodName: "CompleteVerification",
			Handler:    _Onboard_CompleteVerification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/onboard.proto",
}
