syntax = "proto3";

package onboard.v1;

option go_package = "github.com/vocbl/users-svc/internal/port/grpc/pb;pb";

message RegistrationRequest {
    string email = 1;
    string password = 2;
    string firstName = 3;
    string lastName = 4;
    string username = 5;
}

message RegistrationResult {
    string sessionID = 1;
}

service Onboard {
    rpc Register (RegistrationRequest) returns (RegistrationResult);
}

// type NewUser struct {
// 	Email     string
// 	Password  string
// 	FirstName string
// 	LastName  string
// 	Username  string
// }