// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vocbl/users-svc/internal/application/onboard (interfaces: VerificationRepo)
//
// Generated by this command:
//
//	mockgen -destination=./mock/mock_verification_repo.go -package=mock github.com/vocbl/users-svc/internal/application/onboard VerificationRepo
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	app "github.com/vocbl/users-svc/internal/application/onboard"
	domain "github.com/vocbl/users-svc/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockVerificationRepo is a mock of VerificationRepo interface.
type MockVerificationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockVerificationRepoMockRecorder
	isgomock struct{}
}

// MockVerificationRepoMockRecorder is the mock recorder for MockVerificationRepo.
type MockVerificationRepoMockRecorder struct {
	mock *MockVerificationRepo
}

// NewMockVerificationRepo creates a new mock instance.
func NewMockVerificationRepo(ctrl *gomock.Controller) *MockVerificationRepo {
	mock := &MockVerificationRepo{ctrl: ctrl}
	mock.recorder = &MockVerificationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerificationRepo) EXPECT() *MockVerificationRepoMockRecorder {
	return m.recorder
}

// CheckUsernameExistance mocks base method.
func (m *MockVerificationRepo) CheckUsernameExistance(ctx context.Context, username string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUsernameExistance", ctx, username)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUsernameExistance indicates an expected call of CheckUsernameExistance.
func (mr *MockVerificationRepoMockRecorder) CheckUsernameExistance(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUsernameExistance", reflect.TypeOf((*MockVerificationRepo)(nil).CheckUsernameExistance), ctx, username)
}

// Clean mocks base method.
func (m *MockVerificationRepo) Clean(ctx context.Context, cleanUpVerificationDuration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clean", ctx, cleanUpVerificationDuration)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clean indicates an expected call of Clean.
func (mr *MockVerificationRepoMockRecorder) Clean(ctx, cleanUpVerificationDuration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clean", reflect.TypeOf((*MockVerificationRepo)(nil).Clean), ctx, cleanUpVerificationDuration)
}

// Create mocks base method.
func (m *MockVerificationRepo) Create(ctx context.Context, session *domain.UserVerificationSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockVerificationRepoMockRecorder) Create(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVerificationRepo)(nil).Create), ctx, session)
}

// CreateUser mocks base method.
func (m *MockVerificationRepo) CreateUser(ctx context.Context, user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockVerificationRepoMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockVerificationRepo)(nil).CreateUser), ctx, user)
}

// Delete mocks base method.
func (m *MockVerificationRepo) Delete(ctx context.Context, sessionID domain.VerificationSessionID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVerificationRepoMockRecorder) Delete(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVerificationRepo)(nil).Delete), ctx, sessionID)
}

// EmitUserVerifiedEvent mocks base method.
func (m *MockVerificationRepo) EmitUserVerifiedEvent(ctx context.Context, sessionID domain.VerificationSessionID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmitUserVerifiedEvent", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// EmitUserVerifiedEvent indicates an expected call of EmitUserVerifiedEvent.
func (mr *MockVerificationRepoMockRecorder) EmitUserVerifiedEvent(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmitUserVerifiedEvent", reflect.TypeOf((*MockVerificationRepo)(nil).EmitUserVerifiedEvent), ctx, sessionID)
}

// EmitVerificationSessionCreatedEvent mocks base method.
func (m *MockVerificationRepo) EmitVerificationSessionCreatedEvent(ctx context.Context, sessionID domain.VerificationSessionID, email domain.Email, password domain.Password) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmitVerificationSessionCreatedEvent", ctx, sessionID, email, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// EmitVerificationSessionCreatedEvent indicates an expected call of EmitVerificationSessionCreatedEvent.
func (mr *MockVerificationRepoMockRecorder) EmitVerificationSessionCreatedEvent(ctx, sessionID, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmitVerificationSessionCreatedEvent", reflect.TypeOf((*MockVerificationRepo)(nil).EmitVerificationSessionCreatedEvent), ctx, sessionID, email, password)
}

// EmitVerificationSessionStartedEvent mocks base method.
func (m *MockVerificationRepo) EmitVerificationSessionStartedEvent(ctx context.Context, sessionID domain.VerificationSessionID, email domain.Email, token domain.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmitVerificationSessionStartedEvent", ctx, sessionID, email, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// EmitVerificationSessionStartedEvent indicates an expected call of EmitVerificationSessionStartedEvent.
func (mr *MockVerificationRepoMockRecorder) EmitVerificationSessionStartedEvent(ctx, sessionID, email, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmitVerificationSessionStartedEvent", reflect.TypeOf((*MockVerificationRepo)(nil).EmitVerificationSessionStartedEvent), ctx, sessionID, email, token)
}

// Get mocks base method.
func (m *MockVerificationRepo) Get(ctx context.Context, sessionID domain.VerificationSessionID) (*domain.UserVerificationSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, sessionID)
	ret0, _ := ret[0].(*domain.UserVerificationSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockVerificationRepoMockRecorder) Get(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVerificationRepo)(nil).Get), ctx, sessionID)
}

// Update mocks base method.
func (m *MockVerificationRepo) Update(ctx context.Context, session *domain.UserVerificationSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockVerificationRepoMockRecorder) Update(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVerificationRepo)(nil).Update), ctx, session)
}

// WithinTransaction mocks base method.
func (m *MockVerificationRepo) WithinTransaction(ctx context.Context, fn func(app.VerificationRepo) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithinTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithinTransaction indicates an expected call of WithinTransaction.
func (mr *MockVerificationRepoMockRecorder) WithinTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithinTransaction", reflect.TypeOf((*MockVerificationRepo)(nil).WithinTransaction), ctx, fn)
}
