// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vocbl/users-svc/internal/application/onboard (interfaces: VerificationStarterRepo)
//
// Generated by this command:
//
//	mockgen -destination=./mock/mock_verification_starter_repo.go -package=mock github.com/vocbl/users-svc/internal/application/onboard VerificationStarterRepo
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	app "github.com/vocbl/users-svc/internal/application/onboard"
	domain "github.com/vocbl/users-svc/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockVerificationStarterRepo is a mock of VerificationStarterRepo interface.
type MockVerificationStarterRepo struct {
	ctrl     *gomock.Controller
	recorder *MockVerificationStarterRepoMockRecorder
	isgomock struct{}
}

// MockVerificationStarterRepoMockRecorder is the mock recorder for MockVerificationStarterRepo.
type MockVerificationStarterRepoMockRecorder struct {
	mock *MockVerificationStarterRepo
}

// NewMockVerificationStarterRepo creates a new mock instance.
func NewMockVerificationStarterRepo(ctrl *gomock.Controller) *MockVerificationStarterRepo {
	mock := &MockVerificationStarterRepo{ctrl: ctrl}
	mock.recorder = &MockVerificationStarterRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerificationStarterRepo) EXPECT() *MockVerificationStarterRepoMockRecorder {
	return m.recorder
}

// EmitVerificationSessionStartedEvent mocks base method.
func (m *MockVerificationStarterRepo) EmitVerificationSessionStartedEvent(ctx context.Context, sessionID domain.VerificationSessionID, email domain.Email, token domain.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmitVerificationSessionStartedEvent", ctx, sessionID, email, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// EmitVerificationSessionStartedEvent indicates an expected call of EmitVerificationSessionStartedEvent.
func (mr *MockVerificationStarterRepoMockRecorder) EmitVerificationSessionStartedEvent(ctx, sessionID, email, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmitVerificationSessionStartedEvent", reflect.TypeOf((*MockVerificationStarterRepo)(nil).EmitVerificationSessionStartedEvent), ctx, sessionID, email, token)
}

// Get mocks base method.
func (m *MockVerificationStarterRepo) Get(ctx context.Context, sessionID domain.VerificationSessionID) (*domain.UserVerificationSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, sessionID)
	ret0, _ := ret[0].(*domain.UserVerificationSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockVerificationStarterRepoMockRecorder) Get(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVerificationStarterRepo)(nil).Get), ctx, sessionID)
}

// Update mocks base method.
func (m *MockVerificationStarterRepo) Update(ctx context.Context, session *domain.UserVerificationSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockVerificationStarterRepoMockRecorder) Update(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVerificationStarterRepo)(nil).Update), ctx, session)
}

// WithinTransaction mocks base method.
func (m *MockVerificationStarterRepo) WithinTransaction(ctx context.Context, fn func(app.VerificationStarterRepo) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithinTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithinTransaction indicates an expected call of WithinTransaction.
func (mr *MockVerificationStarterRepoMockRecorder) WithinTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithinTransaction", reflect.TypeOf((*MockVerificationStarterRepo)(nil).WithinTransaction), ctx, fn)
}
