// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vocbl/users-svc/internal/application/onboard (interfaces: OnboardRepo)
//
// Generated by this command:
//
//	mockgen -destination=./mock/mock_onboard_repo.go -package=mock github.com/vocbl/users-svc/internal/application/onboard OnboardRepo
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	ulid "github.com/oklog/ulid"
	app "github.com/vocbl/users-svc/internal/application/onboard"
	domain "github.com/vocbl/users-svc/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockOnboardRepo is a mock of OnboardRepo interface.
type MockOnboardRepo struct {
	ctrl     *gomock.Controller
	recorder *MockOnboardRepoMockRecorder
	isgomock struct{}
}

// MockOnboardRepoMockRecorder is the mock recorder for MockOnboardRepo.
type MockOnboardRepoMockRecorder struct {
	mock *MockOnboardRepo
}

// NewMockOnboardRepo creates a new mock instance.
func NewMockOnboardRepo(ctrl *gomock.Controller) *MockOnboardRepo {
	mock := &MockOnboardRepo{ctrl: ctrl}
	mock.recorder = &MockOnboardRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOnboardRepo) EXPECT() *MockOnboardRepoMockRecorder {
	return m.recorder
}

// CheckUsernameExistance mocks base method.
func (m *MockOnboardRepo) CheckUsernameExistance(ctx context.Context, username string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUsernameExistance", ctx, username)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUsernameExistance indicates an expected call of CheckUsernameExistance.
func (mr *MockOnboardRepoMockRecorder) CheckUsernameExistance(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUsernameExistance", reflect.TypeOf((*MockOnboardRepo)(nil).CheckUsernameExistance), ctx, username)
}

// CleanUpVerificationSessions mocks base method.
func (m *MockOnboardRepo) CleanUpVerificationSessions(ctx context.Context, cleanUpVerificationDuration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanUpVerificationSessions", ctx, cleanUpVerificationDuration)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanUpVerificationSessions indicates an expected call of CleanUpVerificationSessions.
func (mr *MockOnboardRepoMockRecorder) CleanUpVerificationSessions(ctx, cleanUpVerificationDuration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanUpVerificationSessions", reflect.TypeOf((*MockOnboardRepo)(nil).CleanUpVerificationSessions), ctx, cleanUpVerificationDuration)
}

// CompleteUserVerificationSession mocks base method.
func (m *MockOnboardRepo) CompleteUserVerificationSession(ctx context.Context, hashedToken string) (*domain.UserVerificationSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteUserVerificationSession", ctx, hashedToken)
	ret0, _ := ret[0].(*domain.UserVerificationSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteUserVerificationSession indicates an expected call of CompleteUserVerificationSession.
func (mr *MockOnboardRepoMockRecorder) CompleteUserVerificationSession(ctx, hashedToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteUserVerificationSession", reflect.TypeOf((*MockOnboardRepo)(nil).CompleteUserVerificationSession), ctx, hashedToken)
}

// DeleteUserVerificationSession mocks base method.
func (m *MockOnboardRepo) DeleteUserVerificationSession(ctx context.Context, sessionID ulid.ULID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserVerificationSession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserVerificationSession indicates an expected call of DeleteUserVerificationSession.
func (mr *MockOnboardRepoMockRecorder) DeleteUserVerificationSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserVerificationSession", reflect.TypeOf((*MockOnboardRepo)(nil).DeleteUserVerificationSession), ctx, sessionID)
}

// EmitUserCreatedEvent mocks base method.
func (m *MockOnboardRepo) EmitUserCreatedEvent(ctx context.Context, sessionID, email, password, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmitUserCreatedEvent", ctx, sessionID, email, password, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// EmitUserCreatedEvent indicates an expected call of EmitUserCreatedEvent.
func (mr *MockOnboardRepoMockRecorder) EmitUserCreatedEvent(ctx, sessionID, email, password, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmitUserCreatedEvent", reflect.TypeOf((*MockOnboardRepo)(nil).EmitUserCreatedEvent), ctx, sessionID, email, password, token)
}

// EmitUserVerifiedEvent mocks base method.
func (m *MockOnboardRepo) EmitUserVerifiedEvent(ctx context.Context, sessionID ulid.ULID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmitUserVerifiedEvent", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// EmitUserVerifiedEvent indicates an expected call of EmitUserVerifiedEvent.
func (mr *MockOnboardRepoMockRecorder) EmitUserVerifiedEvent(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmitUserVerifiedEvent", reflect.TypeOf((*MockOnboardRepo)(nil).EmitUserVerifiedEvent), ctx, sessionID)
}

// EmitVerifyUserEvent mocks base method.
func (m *MockOnboardRepo) EmitVerifyUserEvent(ctx context.Context, email, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmitVerifyUserEvent", ctx, email, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// EmitVerifyUserEvent indicates an expected call of EmitVerifyUserEvent.
func (mr *MockOnboardRepoMockRecorder) EmitVerifyUserEvent(ctx, email, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmitVerifyUserEvent", reflect.TypeOf((*MockOnboardRepo)(nil).EmitVerifyUserEvent), ctx, email, token)
}

// GetVerificationSessionExpirationTime mocks base method.
func (m *MockOnboardRepo) GetVerificationSessionExpirationTime(ctx context.Context, sessionID ulid.ULID) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVerificationSessionExpirationTime", ctx, sessionID)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVerificationSessionExpirationTime indicates an expected call of GetVerificationSessionExpirationTime.
func (mr *MockOnboardRepoMockRecorder) GetVerificationSessionExpirationTime(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVerificationSessionExpirationTime", reflect.TypeOf((*MockOnboardRepo)(nil).GetVerificationSessionExpirationTime), ctx, sessionID)
}

// RestartUserVerificationSession mocks base method.
func (m *MockOnboardRepo) RestartUserVerificationSession(ctx context.Context, sessionID ulid.ULID, restartableSince time.Time, hashedToken string) (string, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestartUserVerificationSession", ctx, sessionID, restartableSince, hashedToken)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RestartUserVerificationSession indicates an expected call of RestartUserVerificationSession.
func (mr *MockOnboardRepoMockRecorder) RestartUserVerificationSession(ctx, sessionID, restartableSince, hashedToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestartUserVerificationSession", reflect.TypeOf((*MockOnboardRepo)(nil).RestartUserVerificationSession), ctx, sessionID, restartableSince, hashedToken)
}

// SaveUser mocks base method.
func (m *MockOnboardRepo) SaveUser(ctx context.Context, user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveUser indicates an expected call of SaveUser.
func (mr *MockOnboardRepoMockRecorder) SaveUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUser", reflect.TypeOf((*MockOnboardRepo)(nil).SaveUser), ctx, user)
}

// SaveUserExternalIdentity mocks base method.
func (m *MockOnboardRepo) SaveUserExternalIdentity(ctx context.Context, email string, identity domain.ExternalIdentity) (ulid.ULID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUserExternalIdentity", ctx, email, identity)
	ret0, _ := ret[0].(ulid.ULID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveUserExternalIdentity indicates an expected call of SaveUserExternalIdentity.
func (mr *MockOnboardRepoMockRecorder) SaveUserExternalIdentity(ctx, email, identity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUserExternalIdentity", reflect.TypeOf((*MockOnboardRepo)(nil).SaveUserExternalIdentity), ctx, email, identity)
}

// SaveUserVerificationSession mocks base method.
func (m *MockOnboardRepo) SaveUserVerificationSession(ctx context.Context, session *domain.UserVerificationSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUserVerificationSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveUserVerificationSession indicates an expected call of SaveUserVerificationSession.
func (mr *MockOnboardRepoMockRecorder) SaveUserVerificationSession(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUserVerificationSession", reflect.TypeOf((*MockOnboardRepo)(nil).SaveUserVerificationSession), ctx, session)
}

// SetUserVerificationSessionPasswordHash mocks base method.
func (m *MockOnboardRepo) SetUserVerificationSessionPasswordHash(ctx context.Context, sessionID ulid.ULID, passwordHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserVerificationSessionPasswordHash", ctx, sessionID, passwordHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserVerificationSessionPasswordHash indicates an expected call of SetUserVerificationSessionPasswordHash.
func (mr *MockOnboardRepoMockRecorder) SetUserVerificationSessionPasswordHash(ctx, sessionID, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserVerificationSessionPasswordHash", reflect.TypeOf((*MockOnboardRepo)(nil).SetUserVerificationSessionPasswordHash), ctx, sessionID, passwordHash)
}

// WithinTransaction mocks base method.
func (m *MockOnboardRepo) WithinTransaction(ctx context.Context, fn func(app.OnboardRepo) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithinTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithinTransaction indicates an expected call of WithinTransaction.
func (mr *MockOnboardRepoMockRecorder) WithinTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithinTransaction", reflect.TypeOf((*MockOnboardRepo)(nil).WithinTransaction), ctx, fn)
}
