// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/v1/onboard.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckUsernameAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUsernameAvailabilityRequest) Reset() {
	*x = CheckUsernameAvailabilityRequest{}
	mi := &file_api_v1_onboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUsernameAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUsernameAvailabilityRequest) ProtoMessage() {}

func (x *CheckUsernameAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_onboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUsernameAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckUsernameAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_onboard_proto_rawDescGZIP(), []int{0}
}

func (x *CheckUsernameAvailabilityRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type CheckUsernameAvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAvailable   bool                   `protobuf:"varint,1,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUsernameAvailabilityResponse) Reset() {
	*x = CheckUsernameAvailabilityResponse{}
	mi := &file_api_v1_onboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUsernameAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUsernameAvailabilityResponse) ProtoMessage() {}

func (x *CheckUsernameAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_onboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUsernameAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckUsernameAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_onboard_proto_rawDescGZIP(), []int{1}
}

func (x *CheckUsernameAvailabilityResponse) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

type RegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationRequest) Reset() {
	*x = RegistrationRequest{}
	mi := &file_api_v1_onboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationRequest) ProtoMessage() {}

func (x *RegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_onboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationRequest.ProtoReflect.Descriptor instead.
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_onboard_proto_rawDescGZIP(), []int{2}
}

func (x *RegistrationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegistrationRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegistrationRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegistrationRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *RegistrationRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type RegistrationSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationSession) Reset() {
	*x = RegistrationSession{}
	mi := &file_api_v1_onboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationSession) ProtoMessage() {}

func (x *RegistrationSession) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_onboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationSession.ProtoReflect.Descriptor instead.
func (*RegistrationSession) Descriptor() ([]byte, []int) {
	return file_api_v1_onboard_proto_rawDescGZIP(), []int{3}
}

func (x *RegistrationSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GoogleRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleRegistrationRequest) Reset() {
	*x = GoogleRegistrationRequest{}
	mi := &file_api_v1_onboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleRegistrationRequest) ProtoMessage() {}

func (x *GoogleRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_onboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleRegistrationRequest.ProtoReflect.Descriptor instead.
func (*GoogleRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_onboard_proto_rawDescGZIP(), []int{4}
}

func (x *GoogleRegistrationRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type VerificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificationRequest) Reset() {
	*x = VerificationRequest{}
	mi := &file_api_v1_onboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationRequest) ProtoMessage() {}

func (x *VerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_onboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationRequest.ProtoReflect.Descriptor instead.
func (*VerificationRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_onboard_proto_rawDescGZIP(), []int{5}
}

func (x *VerificationRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *VerificationRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_api_v1_onboard_proto protoreflect.FileDescriptor

const file_api_v1_onboard_proto_rawDesc = "" +
	"\n" +
	"\x14api/v1/onboard.proto\x12\n" +
	"onboard.v1\x1a\x1bgoogle/protobuf/empty.proto\">\n" +
	" CheckUsernameAvailabilityRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"F\n" +
	"!CheckUsernameAvailabilityResponse\x12!\n" +
	"\fis_available\x18\x01 \x01(\bR\visAvailable\"\x9f\x01\n" +
	"\x13RegistrationRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\"4\n" +
	"\x13RegistrationSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"/\n" +
	"\x19GoogleRegistrationRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"J\n" +
	"\x13VerificationRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token2\x9b\x04\n" +
	"\aOnboard\x12x\n" +
	"\x19CheckUsernameAvailability\x12,.onboard.v1.CheckUsernameAvailabilityRequest\x1a-.onboard.v1.CheckUsernameAvailabilityResponse\x12L\n" +
	"\bRegister\x12\x1f.onboard.v1.RegistrationRequest\x1a\x1f.onboard.v1.RegistrationSession\x12X\n" +
	"\x0eRegisterGoogle\x12%.onboard.v1.GoogleRegistrationRequest\x1a\x1f.onboard.v1.RegistrationSession\x12N\n" +
	"\x13RestartVerification\x12\x1f.onboard.v1.RegistrationSession\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\x12CancelRegistration\x12\x1f.onboard.v1.RegistrationSession\x1a\x16.google.protobuf.Empty\x12O\n" +
	"\x14CompleteVerification\x12\x1f.onboard.v1.VerificationRequest\x1a\x16.google.protobuf.EmptyB5Z3github.com/vocbl/users-svc/internal/port/grpc/pb;pbb\x06proto3"

var (
	file_api_v1_onboard_proto_rawDescOnce sync.Once
	file_api_v1_onboard_proto_rawDescData []byte
)

func file_api_v1_onboard_proto_rawDescGZIP() []byte {
	file_api_v1_onboard_proto_rawDescOnce.Do(func() {
		file_api_v1_onboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_onboard_proto_rawDesc), len(file_api_v1_onboard_proto_rawDesc)))
	})
	return file_api_v1_onboard_proto_rawDescData
}

var file_api_v1_onboard_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_v1_onboard_proto_goTypes = []any{
	(*CheckUsernameAvailabilityRequest)(nil),  // 0: onboard.v1.CheckUsernameAvailabilityRequest
	(*CheckUsernameAvailabilityResponse)(nil), // 1: onboard.v1.CheckUsernameAvailabilityResponse
	(*RegistrationRequest)(nil),               // 2: onboard.v1.RegistrationRequest
	(*RegistrationSession)(nil),               // 3: onboard.v1.RegistrationSession
	(*GoogleRegistrationRequest)(nil),         // 4: onboard.v1.GoogleRegistrationRequest
	(*VerificationRequest)(nil),               // 5: onboard.v1.VerificationRequest
	(*emptypb.Empty)(nil),                     // 6: google.protobuf.Empty
}
var file_api_v1_onboard_proto_depIdxs = []int32{
	0, // 0: onboard.v1.Onboard.CheckUsernameAvailability:input_type -> onboard.v1.CheckUsernameAvailabilityRequest
	2, // 1: onboard.v1.Onboard.Register:input_type -> onboard.v1.RegistrationRequest
	4, // 2: onboard.v1.Onboard.RegisterGoogle:input_type -> onboard.v1.GoogleRegistrationRequest
	3, // 3: onboard.v1.Onboard.RestartVerification:input_type -> onboard.v1.RegistrationSession
	3, // 4: onboard.v1.Onboard.CancelRegistration:input_type -> onboard.v1.RegistrationSession
	5, // 5: onboard.v1.Onboard.CompleteVerification:input_type -> onboard.v1.VerificationRequest
	1, // 6: onboard.v1.Onboard.CheckUsernameAvailability:output_type -> onboard.v1.CheckUsernameAvailabilityResponse
	3, // 7: onboard.v1.Onboard.Register:output_type -> onboard.v1.RegistrationSession
	3, // 8: onboard.v1.Onboard.RegisterGoogle:output_type -> onboard.v1.RegistrationSession
	6, // 9: onboard.v1.Onboard.RestartVerification:output_type -> google.protobuf.Empty
	6, // 10: onboard.v1.Onboard.CancelRegistration:output_type -> google.protobuf.Empty
	6, // 11: onboard.v1.Onboard.CompleteVerification:output_type -> google.protobuf.Empty
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_onboard_proto_init() }
func file_api_v1_onboard_proto_init() {
	if File_api_v1_onboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_onboard_proto_rawDesc), len(file_api_v1_onboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_onboard_proto_goTypes,
		DependencyIndexes: file_api_v1_onboard_proto_depIdxs,
		MessageInfos:      file_api_v1_onboard_proto_msgTypes,
	}.Build()
	File_api_v1_onboard_proto = out.File
	file_api_v1_onboard_proto_goTypes = nil
	file_api_v1_onboard_proto_depIdxs = nil
}
